# Archivo central para consultas SQL o JPQL del proyecto.
# Aqui puedes escribir las queries que usaran los repositorios o servicios.

# Ejemplo:
# product.findAll=SELECT * FROM products
# product.findByBarcode=SELECT * FROM products WHERE barcode = ?
